[package]
name = "java-bindgen-core"
version = "0.1.0-alpha.4"
edition = "2021"
description = "Java Bindgen | Core"
repository = "https://github.com/PawelJastrzebski/java-bindgen"
license = "MIT"
rust-version = "1.70"
keywords = ["java", "jni", "bindings", "jar"]
categories = ["api-bindings"]
exclude = [
    "/docs",
    "/examples",
    "/target",
]

[dependencies]
convert_case = "0.6"
fs2 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
toml = "0.8"

[dev-dependencies]
rand = "0.8.5"
