[package]
name = "java-bindgen-core"
version = "0.1.0-alpha.1"
edition = "2021"
description = "Java Bindgen | Core"
license = "MIT"
rust-version = "1.70"

[dependencies]
convert_case = "0.6"
fs2 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
toml = "0.8"

[dev-dependencies]
rand = "0.8.5"
