[package]
name = "java-bindgen-macro"
version = "0.1.0"
edition = "2021"
description = "Java Bindgen | Macro"
license = "MIT"
rust-version = "1.70"

[lib]
proc-macro = true

[dependencies]
java-bindgen-core = {path = "../java-bindgen-core"}
syn = { version = "2", features = ['full'] }
quote = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8.14"
thiserror = "1.0.61"
convert_case = "0.6.0"
serde_json = "1.0.120"
fs2 = "0.4.3"
