[package]
name = "java-bindgen-macro"
version = "0.1.0-alpha.1"
edition = "2021"
description = "Java Bindgen | Macro"
repository = "https://github.com/PawelJastrzebski/java-bindgen"
license = "MIT"
rust-version = "1.70"
keywords = ["java", "jni", "bindings", "jar"]
categories = ["api-bindings"]
exclude = [
    "/docs",
    "/examples",
    "/target",
]

[lib]
proc-macro = true

[dependencies]
java-bindgen-core = { version = "0.1.0-alpha.1", path = "../java-bindgen-core"}
syn = { version = "2", features = ['full'] }
quote = "1"