[package]
name = "mylib"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
color-eyre = "0.6.3"
convert_case = "0.6.0"
jni = "0.21.1"
shells = "0.2.0"
toml = "0.8.14"


[package.metadata.java-bindgen]
package = "com.test"