[package]
name = "java-bindgen-core"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
fs2 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.61"
toml = "0.8"

[dev-dependencies]
rand = "0.8.5"
