[package]
name = "java-bindgen-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.6.0"
fs2 = "0.4"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.61"
toml = "0.8"

[dev-dependencies]
random = "0.14"
