[package]
name = "java-bindgen-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "java-pack"
path = "src/java-pack.rs"

[[bin]]
name = "java-bindgen-cli"
path = "src/java-bindgen-cli.rs"

[dependencies]
java-bindgen-core = {path = "../java-bindgen-core"}
ansi_term = "0.12.1"
chrono = "0.4.38"
clap = {version = "4.5.8", features = ["cargo"]}
color-eyre = "0.6.3"
convert_case = "0.6.0"
crossterm = "0.27.0"
pad = "0.1.6"
serde = "1"
shells = "0.2.0"
strip-ansi-escapes = "0.2.0"
subprocess = "0.2.9"
